globals:
  project_home: CVX_HOME
  service_module: cvx_services
  datasource_module: cvx_datasources
  macro_module: cvx_macros


service_objects:



targets:

  geocode_OH:
    url: https://places.geo.us-east-2.amazonaws.com/places/v0/indexes/ohio_test/search/text
    method: POST
    headers:
      Content-type: application/json
      X-Amz-Security-Token: 

    request_params:
      - name: text
        value: '21999 CALVERTON RD, OH 44122'

      - name: key
        value: $AMZN_GEO_API_KEY
