#!/usr/bin/env python

'''
Usage:
    ifnofile --sh <filepath> --script <file>
    ifnofile --py <filepath> --script <file>
    ifnofile --py <filepath> --expr <codestr>
'''

import os, sys
import docopt


def main(args):

    path_string = args['<filepath>']
    if path_string[0] == '/':
        file_location = path_string

    else:
        file_location = os.path.join(os.getcwd(), path_string)
    
    if not os.path.exists(file_location):
        if args['--py']:

            if args['--script']:
                with open(args['<file>'], 'r') as f:
                    code_string = f.read()
                
            elif args['--expr']:
                code_string = args['<codestr>']

            exec(code_string)



if __name__ == '__main__':
    args = docopt.docopt(__doc__)
    main(args)